### ISSUE TITLE
problem: trofi ipfs server not being used

### ISSUE THREAD

**Issue by ExcessionAtEsperi** [trofimarket/problems#32]
problem: fetching data from IPFS is very slow

solution: deploy an IPFS node and cache anything used by TroFi

**Comment by ssomraaj** [comment]
try using infura paid node service if that's cost and labour efficient

**Comment by ExcessionAtEsperi** [comment]
deployed to ipfs.trofi.one

@ssomraaj can you test that it works with the client?

**Comment by sujithsomraaj** [comment]
let me check

**Comment by ExcessionAtEsperi** [comment]
The ports are 80 for the gateway, and 5001 for the API

**Comment by ssomraaj** [comment]
@gazhayes this is fixed, using 5001 for fetching and uploading.

**Comment by ssomraaj** [comment]
@ExcessionAtEsperi we can close this issue

**Comment by ExcessionAtEsperi** [comment]
@sujithsomraaj  no we cannot close this issue, it is not solved. Images are still being fetched from ipfs.io

**Comment by ssomraaj** [comment]
@ExcessionAtEsperi this is replaced now.

**Comment by ExcessionAtEsperi** [comment]
Not fixed... Please verify before commenting, this is very basic.

**Comment by ExcessionAtEsperi** [comment]
Not fixed... The market page is using ipfs.io

I would appreciate it if you could pay a little more attention to detail and stop wasting my time.

**Comment by gazhayes** [comment]
fixed in https://github.com/trofimarket/znft-client/pull/4
